version: '3.4'

networks:
  dev:
    driver: bridge

services:
  diary:
    image: docker.io/library/gogo-library
    depends_on:
      - "app_db"
    container_name: gogoLibrary-services
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__PostgreSql=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=GogoLibraryDocDb;Pooling=true;
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - dev
  
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=GogoLibraryDocDb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:
      
      
